# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-guess-game
  labels:
    app: number-guess-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-guess-game
  template:
    metadata:
      labels:
        app: number-guess-game
    spec:
      containers:
      - name: number-guess-game
        image: ajs3ra8/number-guess-game:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000