# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: number-guess-game
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: number-guess-game.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: number-guess-game
            port:
              number: 80

